# ---------------------------------------------------------------------------
# MODERNDBS
# ---------------------------------------------------------------------------

stages:
    - build
    - test
    - cleanup

make:
    stage: build
    script: 
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make
    artifacts:
        paths:
            - build/external_sort
            - build/tester
        expire_in: 1 hrs
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - build/vendor/
        policy: pull-push
    tags:
        - "clang-7"
        - "cmake"
        - "python3"

tester:
    stage: test
    script:
        - cd build
        - ./tester --gtest_filter='-*Advanced*:*Multithread*'

multithread_tester:
    stage: test
    script:
        - cd build
        - timeout -s INT 30s ./tester --gtest_filter='*Multithread*'

advanced_tester:
    stage: test
    script:
        - cd build
        - ./tester --gtest_filter='*Advanced*'
    allow_failure: true

lint:
    stage: test
    script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make lint
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - build/vendor/
        policy: pull-push
    tags:
        - "clang-7"
        - "clang-tidy-7"
        - "cmake"
        - "python3"
    allow_failure: true
